export const CHANGE_DJRADIO_CATELIST = "CHANGE_DJRADIO_CATELIST";
export const CHANGE_DJRADIO_PROGRAM_RECOMMEND = "CHANGE_DJRADIO_PROGRAM_RECOMMEND";
export const CHANGE_DJRADIO_PROGRAM_TOPLIST = "CHANGE_DJRADIO_PROGRAM_TOPLIST";
export const CHANGE_DJRADIO_RECOMMEND_TYPE = "CHANGE_DJRADIO_RECOMMEND_TYPE";
export const CHANGE_DJRADIO_EXCELLENTDJRADIO = "CHANGE_DJRADIO_EXCELLENTDJRADIO";
export const CHANGE_DJRADIO_RECOMMEND_HOT = "CHANGE_DJRADIO_RECOMMEND_HOT";

