
export const PER_PAGE_NUMBER = 35;

export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
export const CHANGE_CURRENT_CATEGORY = 'CHANGE_CURRENT_CATEGORY';
export const CHANGE_CATEGORY_SONGS = 'CHANGE_CATEGORY_SONGS';