export const CHANGE_TOP_PRTISTS = "CHANGE_TOP_PRTISTS";
export const CHANGE_ARISTCLASSIFYLIST = "CHANGE_ARISTCLASSIFYLIST";
export const CHANGE_CHANGE_ARISTCLASSIFY_AREA = "CHANGE_CHANGE_ARISTCLASSIFY_AREA";
export const CHANGE_CHANGE_ARISTCLASSIFY_TYPE = "CHANGE_CHANGE_ARISTCLASSIFY_TYPE";