export const CHANGE_PLAYLIST_DETAIL = 'CHANGE_PLAYLIST_DETAIL';
export const CHANGE_PLAYLIST_COMMENT = 'CHANGE_PLAYLIST_COMMENT';
export const CHANGE_RELATED_PLAYLIST = 'CHANGE_RELATED_PLAYLIST';
export const CHANGE_PLAYLIST_SUBCRIBERS = 'CHANGE_PLAYLIST_SUBCRIBERS';