export const CHANGE_TOP_BANNERS = 'CHANGE_TOP_BANNERS';
export const CHANGE_HOT_RECOMMEND = 'CHANGE_HOT_RECOMMEND';
export const CHANGE_NEW_ALBUM = 'CHANGE_NEW_ALBUM';

// 榜单接口
export const CHANGE_UP_RANKING = 'CHANGE_UP_RANKING';
export const CHANGE_NEW_RANKING = 'CHANGE_NEW_RANKING';
export const CHANGE_ORIGIN_RANKING = 'CHANGE_ORIGIN_RANKING';

// 所有的榜单
export const CHANGE_ALL_LIST = 'CHANGE_ALL_LIST';

// 
export const CHANGE_SETTLE_SONGER = 'CHANGE_SETTLE_SONGER';
